name = "All the Mods 10"
author = "ATMTeam"
version = "5.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "755d544dc52a09427784cb53e52ba6698c290a943d036c1388effe3b7fb67f71"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
