name = "All the Mods 10"
author = "ATMTeam"
version = "5.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4856a93ca231a96218ca88aee456bb39e4d6ac61f186d98d7ca110a0603dc153"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
