name = "All the Mods 10"
author = "ATMTeam"
version = "5.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dbc279e8bfac5ac679de09a949403b8034faf6227e7d366322ce132f08d3771b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
