name = "All the Mods 10"
author = "ATMTeam"
version = "5.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dfc2656a18b726c5f207a6548fce5f65b7439cae19e09f1a069c9c21c9922845"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
