name = "All the Mods 10"
author = "ATMTeam"
version = "5.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b2b3d05d09fe4bff8b0fba7ccd89186864b1b795f58cf362b210b7a57f0c023"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
