name = "All the Mods 10"
author = "ATMTeam"
version = "5.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a9b2ef4731c7d1afdd6ab8e0f2ddcdd2a6b644e222451dd190c61fbea7754746"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
